### ISSUE TITLE
INTERNALERROR appears when running alongside pytest-flakefinder

### ISSUE THREAD

**Issue by wwuck** [pytest-dev/pytest-plus#30]
I tested adding pytest-plus into the test suite for [keyrings.envvars](https://codeberg.org/wwuck/keyrings.envvars) and it's failing when running alongside pytest-flakefinder.

```
nox > pytest --flake-finder --flake-runs=2 --numprocesses=auto --cov=src/keyrings/envvars/ --cov-report=xml '--log-format='"'"'%(asctime)s %(levelname)s %(message)s'"'"'' '--log-date-format='"'"'%Y-%m-%d %H:%M:%S'"'"'' --log-cli-level=INFO
================================================================================================================================== test session starts ===================================================================================================================================
platform linux -- Python 3.12.1, pytest-7.4.4, pluggy-1.4.0
Using --randomly-seed=3431830401
rootdir: /home/devuan/work/public/keyrings.envvars
configfile: pyproject.toml
plugins: plus-0.6.1, antilru-1.1.1, randomly-3.15.0, xdist-3.5.0, flakefinder-1.1.0, cov-4.1.0
10 workers [80 items]     
scheduling tests via LoadScheduling
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/devuan/work/public/keyrings.envvars/.nox/pytest/lib/python3.12/site-packages/_pytest/main.py", line 271, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>                          ^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/home/devuan/work/public/keyrings.envvars/.nox/pytest/lib/python3.12/site-packages/_pytest/main.py", line 325, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/home/devuan/work/public/keyrings.envvars/.nox/pytest/lib/python3.12/site-packages/pluggy/_hooks.py", line 501, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/home/devuan/work/public/keyrings.envvars/.nox/pytest/lib/python3.12/site-packages/pluggy/_manager.py", line 119, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/home/devuan/work/public/keyrings.envvars/.nox/pytest/lib/python3.12/site-packages/pluggy/_callers.py", line 181, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/home/devuan/work/public/keyrings.envvars/.nox/pytest/lib/python3.12/site-packages/pluggy/_result.py", line 99, in get_result
INTERNALERROR>     raise exc.with_traceback(exc.__traceback__)
INTERNALERROR>   File "/home/devuan/work/public/keyrings.envvars/.nox/pytest/lib/python3.12/site-packages/pluggy/_callers.py", line 102, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>           ^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/home/devuan/work/public/keyrings.envvars/.nox/pytest/lib/python3.12/site-packages/xdist/dsession.py", line 123, in pytest_runtestloop
INTERNALERROR>     self.loop_once()
INTERNALERROR>   File "/home/devuan/work/public/keyrings.envvars/.nox/pytest/lib/python3.12/site-packages/xdist/dsession.py", line 148, in loop_once
INTERNALERROR>     call(**kwargs)
INTERNALERROR>   File "/home/devuan/work/public/keyrings.envvars/.nox/pytest/lib/python3.12/site-packages/xdist/dsession.py", line 187, in worker_workerfinished
INTERNALERROR>     assert not crashitem, (crashitem, node)
INTERNALERROR> AssertionError: ('src/keyrings/envvars/tests/keyring_test.py::TestKeyring::test_get_invalid_service[0]', <WorkerController gw9>)
INTERNALERROR> assert not 'src/keyrings/envvars/tests/keyring_test.py::TestKeyring::test_get_invalid_service[0]'

================================================================================================================================= no tests ran in 1.10s ==================================================================================================================================
nox > Command pytest --flake-finder --flake-runs=2 --numprocesses=auto --cov=src/keyrings/envvars/ --cov-report=xml '--log-format='"'"'%(asctime)s %(levelname)s %(message)s'"'"'' '--log-date-format='"'"'%Y-%m-%d %H:%M:%S'"'"'' --log-cli-level=INFO failed with exit code 3
nox > Session pytest failed.
```

Is this configuration not supported by pytest-plus?

**Comment by ssbarnea** [comment]
There are hundreds of pytest plugins around so testing with all of them is impossible. Still, if you find a problem within this plugin and make a PR to make it compatible with the other one, I will be happy to review it and release the fix.
